name: win+mac+linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-everything:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install ebiten linux deps
      if: runner.os == 'Linux'
      run: make deps-debian

    - run: make

    - name: Upload ${{ runner.os }} build
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }} shark
        path: dist/*

    - name: Cross-compile Windows build
      if: runner.os == 'Linux'
      run: make win

    - name: Upload cross-compiled Windows build
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: Windows shark
        path: dist/*.exe
