name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-linux-win:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install ebiten deps
      run: sudo apt-get install -y libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

    - name: Build
      run: |
        make linux
        make win

    - name: Upload Linux build
      uses: actions/upload-artifact@v3
      with:
        name: Linux build
        path: dist/shark-linux

    - name: Upload Windows build
      uses: actions/upload-artifact@v3
      with:
        name: Windows build
        path: dist/shark-win.exe

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - run: make mac

    - name: Upload macOS build
      uses: actions/upload-artifact@v3
      with:
        name: macOS build
        path: dist/shark-mac
