name: win+mac+linux

on:
  push

jobs:

  build-everything:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install ebiten linux deps
      if: runner.os == 'Linux'
      run: make deps-debian

    - name: Build for ${{ runner.os }}
      run: make $(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')
      # The `tr` stuff is to convert the string to lowercase

    - name: Upload ${{ runner.os }} build
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }} shark
        path: dist/*

    - name: Cross-compile Windows build
      if: runner.os == 'Linux'
      run: make windows

    - name: Upload cross-compiled Windows build
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: Windows shark
        path: dist/*.exe

    - name: Upload artifacts to tagged release
      if: github.ref_type == 'tag'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
      run: |
        # Because we have multiple OSes in the build matrix, we need to either
        # create a new release, or upload to the release if it already exists.
        if gh release view "$TAG"; then
          gh release upload "$TAG" dist/*
        else
          gh release create "$TAG" dist/* --generate-notes
        fi
